#checkout action: Fetches the contents of your repository (i.e., checks out your code) into the runner environment where your workflow is executing.
#setup-python action: Sets up the Python environment in your GitHub Actions runner, allowing you to specify the version of Python you want to use and setting up the appropriate environment variables.

name: CI/CD Pipeline
on: #  on push work as trigger which tell agent/assitant to run every thing which below push
  push: # and 1st step is to getting code from github

jobs: # jobs me that action/task you need to perform
  build:
    runs-on: windows-latest

    steps: # in which agent run  the task and what should be done there.
    # 1st step(in which we tell to agent get code,setup python envoirment or cml)
      - name: Checkout code from GitHub repository # uses mean use another github user's actionI
        uses: actions/checkout@v2 # action use for getting source code of project from git hub repo && checkout is type of action and v is version 

      - name: Python Setup
        uses: action/setup-python@v4
        with:
          python-version: 3.11

# now istall dependencies
      - name: install  dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: run main/app file
        run: |
          python app.py


#this step is not necessary but for CI in ML we use it.And can also dvc@v....
      - name: ForTracking 
        uses: iterative/setup-cml@v2 # cml-> CML stand for continous machine learing. iterative is company name which build it


      - name: Create CML  Report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "# Data Report " >> report.md
          echo "## Bar Plot" >> report.md
          echo "![](./fruits_bar_plot.png "Bar plot")">> report.md
          echo "## line Plot" >> report.md
          echo "![](./fruits_line_plot.png "line plot")">> report.md
          
          cml comment Create report.md



        

          
        
  
    